global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
  - "rules.yml"
scrape_configs:
  - job_name: 'python_api'
    static_configs:
    - targets: ['app:80']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']
