groups:
  - name: simple_alert
    rules:
      - alert: ManyAboutCalls
        expr: sum(increase(about_call_total[1m])) >= 50
        labels:
          severity: critical
        annotations:
          summary: Many api calls to about endpoint
          runbook: https://github.com/tiagotele/python_api/runbook/ManyAboutCalls.md
      - alert: Some application is not running
        expr: up == 0
        labels:
          severity: critical
        annotations:
          summary: Example of sumary
          runbook: https://github.com/tiagotele/python_api/runbook/Some_application_is_not_running.md
